table dim_date
	lineageTag: 71dcb3b5-d600-5314-a1be-2dcdb0398c55
	dataCategory: Time

	column date_key
		dataType: int64
		isHidden
		lineageTag: a7bc59dd-8f23-5edc-a9c4-479baa6ba319
		summarizeBy: none
		sourceColumn: date_key

		annotation SummarizationSetBy = Automatic

	column date
		dataType: dateTime
		isKey
		formatString: yyyy-mm-dd
		lineageTag: 919b406c-1e35-5493-b3d2-1ba0a0a93d87
		summarizeBy: none
		sourceColumn: date

		annotation SummarizationSetBy = Automatic

	column year
		dataType: int64
		lineageTag: b505676a-16ef-50a3-b46b-c28d582a0c4f
		summarizeBy: none
		sourceColumn: year

		annotation SummarizationSetBy = Automatic

	column quarter
		dataType: int64
		lineageTag: 1ff283d0-303c-52c2-aa9d-27654f7a2045
		summarizeBy: none
		sourceColumn: quarter

		annotation SummarizationSetBy = Automatic

	column quarter_label
		dataType: string
		sortByColumn: quarter
		lineageTag: b69d0a8f-d6a5-5028-9d89-0e1b275ae91c
		summarizeBy: none
		sourceColumn: quarter_label

		annotation SummarizationSetBy = Automatic

	column month
		dataType: int64
		lineageTag: 0a710f87-e477-5244-9915-82d42daa1afd
		summarizeBy: none
		sourceColumn: month

		annotation SummarizationSetBy = Automatic

	column month_name
		dataType: string
		sortByColumn: month
		lineageTag: e57f3eba-385a-51df-be99-352b0ee58418
		summarizeBy: none
		sourceColumn: month_name

		annotation SummarizationSetBy = Automatic

	column year_month
		dataType: string
		lineageTag: a121b034-6713-5c87-af9e-b92f21559ea5
		summarizeBy: none
		sourceColumn: year_month

		annotation SummarizationSetBy = Automatic

	column month_start_date
		dataType: dateTime
		formatString: yyyy-mm-dd
		lineageTag: fc5d9f84-1d3e-56dd-ab9f-93bca13140c5
		summarizeBy: none
		sourceColumn: month_start_date

		annotation SummarizationSetBy = Automatic

	column week_of_year
		dataType: int64
		lineageTag: 36964439-47d7-5ea5-a696-df163e4597f1
		summarizeBy: none
		sourceColumn: week_of_year

		annotation SummarizationSetBy = Automatic

	column day_of_week
		dataType: int64
		lineageTag: 813a1287-4425-5ac4-8a0d-1bafa8f77358
		summarizeBy: none
		sourceColumn: day_of_week

		annotation SummarizationSetBy = Automatic

	column day_name
		dataType: string
		sortByColumn: day_of_week
		lineageTag: 07be6d24-b4c8-5d98-b2c3-bffaafaac7bb
		summarizeBy: none
		sourceColumn: day_name

		annotation SummarizationSetBy = Automatic

	column is_weekend
		dataType: int64
		lineageTag: 3ffbcc63-a9d2-594b-a44e-090f806fca19
		summarizeBy: none
		sourceColumn: is_weekend

		annotation SummarizationSetBy = Automatic

	column is_reporting_period
		dataType: int64
		lineageTag: 80b59994-2bc3-558a-a663-6ac5fd461260
		summarizeBy: none
		sourceColumn: is_reporting_period

		annotation SummarizationSetBy = Automatic

	partition dim_date = m
		mode: import
		source =
				let
				    Source = Csv.Document(File.Contents(DataFolder & "\dim_date.csv"), [Delimiter = ",", Columns = 14, Encoding = 65001, QuoteStyle = QuoteStyle.Csv]),
				    #"Promoted Headers" = Table.PromoteHeaders(Source, [PromoteAllScalars = true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers", {{"date_key", Int64.Type}, {"date", type date}, {"year", Int64.Type}, {"quarter", Int64.Type}, {"quarter_label", type text}, {"month", Int64.Type}, {"month_name", type text}, {"year_month", type text}, {"month_start_date", type date}, {"week_of_year", Int64.Type}, {"day_of_week", Int64.Type}, {"day_name", type text}, {"is_weekend", Int64.Type}, {"is_reporting_period", Int64.Type}}, "en-US")
				in
				    #"Changed Type"

	annotation PBI_ResultType = Table
