"""Assemble notebooks/claims_analysis.ipynb from cells defined here (then execute with nbconvert)."""

from pathlib import Path

import nbformat as nbf

ROOT = Path(__file__).resolve().parents[1]
nb = nbf.v4.new_notebook()
cells = []


def md(s):
    cells.append(nbf.v4.new_markdown_cell(s.strip()))


def code(s):
    cells.append(nbf.v4.new_code_cell(s.strip()))


md("""
# Health Insurance Claims & Fraud Signals Analysis

**Perspective:** a commercial health plan's claims analytics team, reviewing two years of claims
(Jan 2024 – Dec 2025, data as of 2025-12-31) across three lenses:

| Lens | Questions | Queries |
|---|---|---|
| **Payer efficiency** | Where do denials come from? How fast do we adjudicate? | 01, 02, 03, 05, 06 |
| **Cost containment** | Which conditions and members drive spend? What is the cost trend? | 04, 07, 08, 12 |
| **Claims integrity** | Are duplicates, billing outliers, or provider patterns leaking dollars? | 09, 10, 11 |

Each section loads a query from `../sql/`, runs it against `../data/claims.db`, shows the result, and charts it.
Charts are also saved to `../images/` and results to `../data/results/` (used by the README and slide deck).

> All data is synthetic, generated by `scripts/generate_data.py`.
""")

code("""
import sqlite3
from pathlib import Path

import matplotlib.pyplot as plt
import matplotlib.ticker as mtick
import pandas as pd

ROOT = Path.cwd() if (Path.cwd() / "data" / "claims.db").exists() else Path.cwd().parent
SQL_DIR, IMG_DIR, RES_DIR = ROOT / "sql", ROOT / "images", ROOT / "data" / "results"
IMG_DIR.mkdir(exist_ok=True); RES_DIR.mkdir(exist_ok=True)
con = sqlite3.connect(ROOT / "data" / "claims.db")

# Palette: navy ink + teal primary; coral reserved for risk/flags. Validated for CVD separation.
NAVY, TEAL, CORAL, BLUE, GOLD = "#0B1F3A", "#0F9D8F", "#E0694F", "#3B6FB6", "#B8892A"
MUTED, GRID = "#6B7280", "#E5E7EB"
plt.rcParams.update({
    "figure.dpi": 110, "savefig.dpi": 150, "figure.facecolor": "white",
    "axes.edgecolor": GRID, "axes.labelcolor": MUTED, "axes.titleweight": "bold",
    "axes.titlesize": 13, "axes.titlecolor": NAVY, "axes.titlelocation": "left",
    "axes.spines.top": False, "axes.spines.right": False, "axes.grid": True,
    "grid.color": GRID, "grid.linewidth": 0.8, "xtick.color": MUTED, "ytick.color": MUTED,
    "font.size": 10, "legend.frameon": False,
})
pd.set_option("display.max_columns", 30); pd.set_option("display.width", 200)


def run_sql(name: str) -> pd.DataFrame:
    \"\"\"Run sql/<name>.sql, save the result to data/results/<name>.csv and return it.\"\"\"
    df = pd.read_sql((SQL_DIR / f"{name}.sql").read_text(), con)
    df.to_csv(RES_DIR / f"{name}.csv", index=False)
    return df


def save(fig, name):
    fig.tight_layout()
    fig.savefig(IMG_DIR / f"{name}.png", bbox_inches="tight")
    plt.show()


def _money(x, _=None):
    if abs(x) >= 1e6:
        return f"${x/1e6:.1f}M"
    if abs(x) >= 1e3:
        return f"${x/1e3:.1f}K".replace(".0K", "K")
    return f"${x:,.0f}"


money = mtick.FuncFormatter(_money)
""")

md("## 0. Dataset overview")
code("""
tables = ["members", "policies", "providers", "claims", "diagnosis_codes", "procedure_codes", "rejection_reasons"]
overview = pd.DataFrame({"table": tables,
                         "rows": [con.execute(f"SELECT COUNT(*) FROM {t}").fetchone()[0] for t in tables]})
display(overview)

kpi = pd.read_sql(\"\"\"
    SELECT COUNT(*)                                             AS claims,
           ROUND(SUM(billed_amount))                            AS billed,
           ROUND(SUM(COALESCE(approved_amount, 0)))             AS approved,
           ROUND(100.0 * AVG(claim_status = 'Approved'), 1)     AS approved_pct,
           ROUND(100.0 * AVG(claim_status = 'Rejected'), 1)     AS rejected_pct,
           ROUND(100.0 * AVG(claim_status = 'Pending'), 1)      AS pending_pct,
           MIN(service_date) AS first_service, MAX(service_date) AS last_service
    FROM claims\"\"\", con)
kpi.to_csv(RES_DIR / "00_kpis.csv", index=False)
kpi
""")
md("![schema](../images/schema_diagram.png)")

# ------------------------------------------------------------------ efficiency
md("""
---
# Part 1 — Payer efficiency

## Q01. Rejection rate by provider vs. specialty benchmark
Providers with ≥150 adjudicated claims, ranked by how far their rejection rate sits above their specialty's pooled rate.
""")
code("""
q01 = run_sql("01_rejection_rate_by_provider")
q01.head(15)
""")
code("""
top = q01.head(15).iloc[::-1]
labels = top.provider_name.str.slice(0, 28) + "  (" + top.specialty + ")"
fig, ax = plt.subplots(figsize=(10, 6))
ax.barh(labels, top.rejection_rate_pct, color=[CORAL if n == "Out-of-Network" else TEAL for n in top.network_status], height=0.6)
ax.scatter(top.specialty_rate_pct, labels, color=NAVY, marker="|", s=260, linewidths=2.5, zorder=3, label="Specialty rate")
for y, v in enumerate(top.rejection_rate_pct):
    ax.text(v + 0.6, y, f"{v:.0f}%", va="center", color=NAVY, fontsize=9)
ax.xaxis.set_major_formatter(mtick.PercentFormatter())
ax.grid(axis="y", visible=False)
from matplotlib.patches import Patch
from matplotlib.lines import Line2D
ax.legend(handles=[Patch(color=CORAL, label="Out-of-network"), Patch(color=TEAL, label="In-network"),
                   Line2D([0], [0], color=NAVY, marker="|", ls="", ms=14, mew=2.5, label="Specialty rate")],
          loc="upper center", bbox_to_anchor=(0.4, -0.1), ncol=3)
ax.set_title("Providers furthest above their specialty's rejection rate")
save(fig, "q01_rejection_by_provider")
""")
md("""
**Read:** the worst outliers are overwhelmingly **out-of-network** providers billing HMO/EPO members, where the plan has no OON benefit.
That is a *member steering / network adequacy* problem more than a provider-behaviour problem — the fix is referral management
and directory accuracy, not provider education.
""")

md("""
## Q02. Rejection reasons — volume, dollars, and avoidability
""")
code("""
q02 = run_sql("02_rejection_reasons")
q02
""")
code("""
d = q02.iloc[::-1]
fig, ax = plt.subplots(figsize=(10, 5.2))
ax.barh(d.reason_code + "  " + d.description.str.slice(0, 44), d.rejected_claims,
        color=[TEAL if a == "Avoidable" else BLUE for a in d.avoidability], height=0.6)
for y, (n, pct) in enumerate(zip(d.rejected_claims, d.pct_of_rejections)):
    ax.text(n + 80, y, f"{n:,}  ({pct:.0f}%)", va="center", fontsize=9, color=NAVY)
ax.grid(axis="y", visible=False)
ax.legend(handles=[Patch(color=TEAL, label="Avoidable (front-end fixable)"), Patch(color=BLUE, label="Clinical / policy")], loc="lower right")
ax.set_title("Rejected claims by reason")
ax.set_xlabel("Rejected claims")
ax.set_xlim(0, d.rejected_claims.max() * 1.22)
save(fig, "q02_rejection_reasons")
avoid = q02.loc[q02.avoidability == "Avoidable", "rejected_claims"].sum() / q02.rejected_claims.sum()
print(f"Avoidable share of denials: {avoid:.1%}")
""")

md("""
## Q03. Rejection mix by specialty
Conditional aggregation pivots the reason mix per specialty; `ROW_NUMBER()` picks each specialty's top denial driver.
""")
code("""
q03 = run_sql("03_rejection_reason_by_specialty")
q03
""")
code("""
cols = ["out_of_network_pct", "coding_pct", "admin_eligibility_pct", "duplicate_pct", "prior_auth_pct", "clinical_policy_pct"]
nice = ["Out-of-network", "Coding", "Admin / eligibility", "Duplicate", "Prior auth", "Clinical / policy"]
h = q03.set_index("specialty")[cols]
fig, ax = plt.subplots(figsize=(10, 7))
im = ax.imshow(h.values, cmap=plt.cm.colors.LinearSegmentedColormap.from_list("teal", ["#F0FDFA", TEAL, NAVY]), aspect="auto")
ax.set_xticks(range(len(nice)), nice, rotation=25, ha="right")
ax.set_yticks(range(len(h)), [f"{s}  ({r:.1f}%)" for s, r in zip(h.index, q03.rejection_rate_pct)])
for i in range(h.shape[0]):
    for j in range(h.shape[1]):
        v = h.values[i, j]
        ax.text(j, i, f"{v:.0f}", ha="center", va="center", fontsize=8.5, color="white" if v > h.values.max() * 0.45 else NAVY)
ax.grid(False)
ax.set_title("Share of each specialty's denials by reason (%)  —  overall rejection rate in brackets")
fig.colorbar(im, ax=ax, shrink=0.6, label="% of specialty denials")
save(fig, "q03_reason_by_specialty")
""")

md("""
## Q05. Adjudication turnaround time
`julianday()` date math plus window-based median / P90. The **manual-review path** (prior-auth procedures or billed > $2,500) is where the time goes.
""")
code("""
q05 = run_sql("05_approval_turnaround")
q05
""")
code("""
g = q05.assign(label=q05.claim_type + "\\n" + q05.review_path.str.replace(" path", ""))
piv = g.pivot_table(index="label", columns="claim_status", values="median_days")
p90 = g.pivot_table(index="label", columns="claim_status", values="p90_days")
fig, ax = plt.subplots(figsize=(10, 4.8))
x = range(len(piv)); w = 0.36
for k, (status, color) in enumerate([("Approved", TEAL), ("Rejected", CORAL)]):
    xs = [i + (k - 0.5) * w for i in x]
    ax.bar(xs, piv[status], width=w * 0.92, color=color, label=f"{status} — median")
    ax.scatter(xs, p90[status], color=NAVY, marker="_", s=300, linewidths=2, zorder=3)
    for xi, m, p in zip(xs, piv[status], p90[status]):
        ax.text(xi, p + 0.8, f"P90 {p:.0f}", ha="center", fontsize=8, color=MUTED)
        ax.text(xi, m / 2, f"{m:.0f}d", ha="center", color="white", fontsize=9, fontweight="bold")
ax.set_xticks(list(x), piv.index)
ax.set_ylabel("Days from submission to decision")
ax.grid(axis="x", visible=False)
ax.legend(handles=[Patch(color=TEAL, label="Approved (median)"), Patch(color=CORAL, label="Rejected (median)"),
                   Line2D([0], [0], color=NAVY, lw=2, label="P90")], loc="upper left")
ax.set_title("Turnaround: auto-adjudication vs. manual review")
save(fig, "q05_turnaround")
""")

md("""
## Q06. Monthly turnaround trend & SLA compliance
`LAG()` gives month-over-month change; a 3-month rolling average smooths noise. The 2025 auto-adjudication rollout shows up clearly.
""")
code("""
q06 = run_sql("06_turnaround_trend_and_backlog")
q06
""")
code("""
m = pd.to_datetime(q06.month)
fig, (a1, a2) = plt.subplots(1, 2, figsize=(12, 4.2))
a1.plot(m, q06.avg_turnaround_days, color=TEAL, lw=2, marker="o", ms=4, label="Monthly avg")
a1.plot(m, q06.rolling_3m_days, color=NAVY, lw=2, ls="--", label="3-month rolling")
a1.set_title("Average days to adjudicate"); a1.set_ylim(0, None); a1.legend(loc="lower left")
a1.annotate(f"{q06.avg_turnaround_days.iloc[-1]:.1f}d", (m.iloc[-1], q06.avg_turnaround_days.iloc[-1]),
            xytext=(6, -4), textcoords="offset points", color=NAVY, fontweight="bold")
a2.plot(m, q06.pct_within_15d, color=TEAL, lw=2, marker="o", ms=4)
a2.yaxis.set_major_formatter(mtick.PercentFormatter()); a2.set_title("% of claims decided within 15 days")
for a in (a1, a2):
    a.tick_params(axis="x", rotation=45)
save(fig, "q06_turnaround_trend")
backlog = pd.read_sql(\"\"\"
    SELECT CASE WHEN age <= 15 THEN '0-15 days' WHEN age <= 30 THEN '16-30 days'
                WHEN age <= 60 THEN '31-60 days' ELSE '60+ days' END AS age_bucket,
           COUNT(*) AS pending_claims, ROUND(SUM(billed_amount)) AS pending_billed
    FROM (SELECT billed_amount, julianday('2025-12-31') - julianday(submission_date) AS age
          FROM claims WHERE claim_status = 'Pending')
    GROUP BY 1 ORDER BY MIN(age)\"\"\", con)
backlog
""")

# ------------------------------------------------------------------ cost
md("""
---
# Part 2 — Cost containment

## Q04. Average claim cost by diagnosis
A true median in SQLite via `ROW_NUMBER()` + `COUNT()` windows. Mean ≫ median flags diagnoses whose cost is driven by a few expensive episodes (surgery, admissions).
""")
code("""
q04 = run_sql("04_avg_cost_by_diagnosis")
q04
""")
code("""
d = q04.head(14).iloc[::-1]
lab = d.diagnosis_code + "  " + d.description.str.slice(0, 38)
fig, ax = plt.subplots(figsize=(10, 6))
ax.barh(lab, d.avg_approved, color=TEAL, height=0.6, label="Mean approved / claim")
ax.scatter(d.median_approved, lab, color=NAVY, marker="D", s=30, zorder=3, label="Median approved / claim")
for y, v in enumerate(d.avg_approved):
    ax.text(v + 30, y, f"${v:,.0f}", va="center", fontsize=9, color=NAVY)
ax.xaxis.set_major_formatter(money); ax.grid(axis="y", visible=False)
ax.set_xlim(0, max(d.avg_approved.max(), d.median_approved.max()) * 1.12)
ax.legend(loc="lower right"); ax.set_title("Average approved cost per claim — top 14 diagnoses")
save(fig, "q04_cost_by_diagnosis")
""")

md("""
## Q07. High-cost members (top 1%)
`NTILE(100)` isolates the top percentile; `GROUP_CONCAT` summarises each member's chronic-condition categories.
""")
code("""
q07 = run_sql("07_high_cost_members")
q07.head(15)
""")
code("""
print(f"Top-1% members listed: {len(q07)}  |  median age {q07.age.median():.0f}  |  "
      f"median chronic dx {q07.chronic_dx_count.median():.0f}  |  avg spend ${q07.approved_spend.mean():,.0f}")
cats = q07.chronic_categories.dropna().str.split(",").explode().value_counts()
fig, ax = plt.subplots(figsize=(9, 4))
ax.barh(cats.index[::-1], cats.values[::-1], color=TEAL, height=0.6)
for y, v in enumerate(cats.values[::-1]):
    ax.text(v + 0.4, y, f"{v}", va="center", fontsize=9, color=NAVY)
ax.grid(axis="y", visible=False)
ax.set_title(f"Chronic-condition categories among top-{len(q07)} high-cost members")
ax.set_xlabel("Members with at least one claim in category")
save(fig, "q07_high_cost_conditions")
""")

md("## Q08. Cost concentration (Pareto by member decile)")
code("""
q08 = run_sql("08_cost_concentration")
q08
""")
code("""
fig, ax = plt.subplots(figsize=(10, 4.5))
ax.bar(q08.decile, q08.pct_of_spend, color=[TEAL if d == 1 else "#99D5CF" for d in q08.decile], width=0.7)
for x, v, c in zip(q08.decile, q08.pct_of_spend, q08.cumulative_pct_of_spend):
    ax.text(x, v + 1, f"{v:.0f}%", ha="center", fontsize=9, color=NAVY)
ax.set_xticks(q08.decile, [f"D{d}" for d in q08.decile])
ax.yaxis.set_major_formatter(mtick.PercentFormatter()); ax.grid(axis="x", visible=False)
ax.set_xlabel("Member spend decile (D1 = highest-cost 10%)"); ax.set_ylabel("Share of approved spend")
ax.set_title(f"Top 10% of members drive {q08.pct_of_spend.iloc[0]:.0f}% of spend; top 20% drive {q08.cumulative_pct_of_spend.iloc[1]:.0f}%")
save(fig, "q08_cost_concentration")
""")

md("""
## Q12. Month-over-month cost trend and PMPM
Member-months come from a recursive month calendar joined to policy coverage windows. `LAG(1)` = MoM, `LAG(12)` = YoY PMPM trend.
Service months after Oct 2025 are excluded to allow claims run-out.
""")
code("""
q12 = run_sql("12_mom_cost_trends")
q12
""")
code("""
m = pd.to_datetime(q12.month)
fig, (a1, a2) = plt.subplots(1, 2, figsize=(12, 4.2))
a1.plot(m, q12.approved, color=TEAL, lw=2, marker="o", ms=4, label="Approved")
a1.plot(m, q12.rolling_3m_approved, color=NAVY, lw=2, ls="--", label="3-month rolling")
a1.yaxis.set_major_formatter(money); a1.set_ylim(0, None); a1.legend(loc="lower left")
a1.set_title("Monthly approved cost (incurred)")
a2.plot(m, q12.approved_pmpm, color=TEAL, lw=2, marker="o", ms=4)
a2.set_title("Approved PMPM"); a2.yaxis.set_major_formatter(mtick.StrMethodFormatter("${x:,.0f}")); a2.set_ylim(0, None)
yoy = q12.yoy_pmpm_change_pct.dropna()
a2.text(0.02, 0.06, f"2025 YTD avg YoY PMPM change: {yoy.mean():+.1f}%", transform=a2.transAxes, color=NAVY, fontweight="bold")
for a in (a1, a2):
    a.tick_params(axis="x", rotation=45)
save(fig, "q12_cost_trend")
""")

# ------------------------------------------------------------------ integrity
md("""
---
# Part 3 — Claims integrity (fraud, waste & abuse signals)

## Q09. Duplicate claims
Window functions over the key *(member, provider, service date, procedure)* mark every resubmission after the first.
""")
code("""
q09 = run_sql("09_duplicate_claims")
q09
""")
code("""
d = q09.set_index("dup_type")
fig, ax = plt.subplots(figsize=(10, 3.6))
left = 0
for col, color, label in [("caught_by_edits", TEAL, "Caught by edits (R01)"), ("paid_duplicates", CORAL, "Paid"),
                          ("pending_duplicates", GOLD, "Pending")]:
    ax.barh(d.index, d[col], left=left, color=color, label=label, height=0.55, edgecolor="white", linewidth=2)
    left = left + d[col]
for y, (lab, row) in enumerate(d.iterrows()):
    ax.text(row.duplicate_claims + 30, y, f"${row.dollars_paid_on_duplicates:,.0f} paid  ({row.leakage_rate_pct:.0f}% leakage)",
            va="center", fontsize=9, color=NAVY)
ax.invert_yaxis(); ax.grid(axis="y", visible=False); ax.set_xlim(0, d.duplicate_claims.max() * 1.55)
ax.legend(loc="lower right"); ax.set_title("Duplicate submissions: caught vs. paid")
save(fig, "q09_duplicates")
""")
md("""
**Read:** exact duplicates are mostly stopped by front-end edits, but **near-duplicates** (billed amount nudged by 1–3%)
leak at ~3x the rate. Adding a tolerance band to the duplicate edit is a quick, recoverable win.
*Same-day repeat services* are usually legitimate (e.g. two injections) and belong in a post-pay review queue, not an auto-deny rule.
""")

md("""
## Q10. Billed-amount outliers
|z| > 3 within procedure code **and** ≥3x the procedure median. The z-test is written as `(x-μ)² > 9σ²` so it runs on SQLite builds without `SQRT`.
""")
code("""
q10 = run_sql("10_billed_amount_outliers")
print(f"{len(q10):,} outlier claims | billed ${q10.billed_amount.sum():,.0f} | "
      f"approved ${q10.approved_amount.fillna(0).sum():,.0f} | status mix: {q10.claim_status.value_counts().to_dict()}")
q10.head(12)
""")
code("""
by = (q10.groupby(["procedure_code", "claim_status"]).size().unstack(fill_value=0)
          .assign(total=lambda x: x.sum(axis=1)).sort_values("total").tail(12))
lbl = [f"{c}  {q10.loc[q10.procedure_code == c, 'procedure_description'].iloc[0][:34]}" for c in by.index]
fig, ax = plt.subplots(figsize=(10, 5))
left = 0
for status, color in [("Approved", CORAL), ("Rejected", TEAL), ("Pending", GOLD)]:
    if status in by:
        ax.barh(lbl, by[status], left=left, color=color, label=status, height=0.6, edgecolor="white", linewidth=2)
        left = left + by[status]
ax.grid(axis="y", visible=False); ax.legend(loc="lower right")
ax.set_title("Billed-amount outliers by procedure (coral = paid)")
ax.set_xlabel("Outlier claims")
save(fig, "q10_outliers")
""")

md("""
## Q11. Provider fraud-signal scorecard
Five signals, each converted to a within-specialty `PERCENT_RANK()` and blended into a 0–100 score. `red_flags` counts signals at or above the 95th peer percentile.
""")
code("""
q11 = run_sql("11_provider_fraud_risk_score")
q11.head(15)
""")
code("""
d = q11.head(15).iloc[::-1]
lab = d.provider_name.str.slice(0, 30) + "  (" + d.specialty + ")"
fig, ax = plt.subplots(figsize=(10, 6))
ax.barh(lab, d.risk_score, color=[CORAL if f >= 3 else TEAL for f in d.red_flags], height=0.6)
for y, (s, f, mk, up) in enumerate(zip(d.risk_score, d.red_flags, d.markup_ratio, d.pct_99215)):
    ax.text(s + 0.5, y, f"{s:.0f}  ·  {f} flags  ·  {mk:.1f}x markup  ·  {up:.0f}% 99215", va="center", fontsize=8.5, color=NAVY)
ax.set_xlim(0, 150); ax.set_xticks(range(0, 101, 20)); ax.grid(axis="y", visible=False)
ax.legend(handles=[Patch(color=CORAL, label="3+ red flags"), Patch(color=TEAL, label="< 3 red flags")],
          loc="upper center", bbox_to_anchor=(0.35, -0.1), ncol=2)
ax.set_title("SIU referral queue: top 15 providers by composite risk score")
save(fig, "q11_provider_risk")
""")
code("""
# How well does the score separate the pack? Compare the flagged cohort with everyone else.
peer = pd.read_sql(\"\"\"
    SELECT ROUND(SUM(c.billed_amount) / SUM(pc.reference_allowed_amount * c.units), 2) AS markup_ratio,
           ROUND(100.0 * SUM(c.procedure_code = '99215') / SUM(c.procedure_code IN ('99213','99214','99215')), 1) AS pct_99215
    FROM claims c JOIN procedure_codes pc ON pc.procedure_code = c.procedure_code\"\"\", con)
flagged = q11[q11.red_flags >= 3]
print(f"{len(flagged)} providers with 3+ red flags | avg markup {flagged.markup_ratio.mean():.2f}x vs book {peer.markup_ratio[0]:.2f}x | "
      f"99215 share {flagged.pct_99215.mean():.0f}% vs book {peer.pct_99215[0]:.0f}% | approved paid ${flagged.approved_paid.sum():,.0f}")
""")

md("""
---
## Summary

| Lens | Finding | Action |
|---|---|---|
| Efficiency | Most denials are *avoidable* (network, coding, missing info, duplicates) | Front-end claim scrubbing, directory accuracy, provider education by specialty |
| Efficiency | Manual-review claims take ~4-5x longer than auto-adjudicated | Expand auto-adjudication rules; gold-carding for prior-auth |
| Cost | Top 10% of members ≈ half of spend; high-cost members are multi-morbid | Case & disease management targeting; stop-loss review |
| Cost | Double-digit YoY PMPM trend, winter respiratory peaks | Trend monitoring, site-of-care and unit-cost initiatives |
| Integrity | Near-duplicates leak ~3x more than exact duplicates | Add ±5% tolerance to duplicate edit; recover paid dollars |
| Integrity | A small provider cohort combines extreme markups, upcoding and duplicates | Refer to SIU; pre-payment review |

See the project README for the full write-up.
""")
code("con.close()")

nb["cells"] = cells
nb["metadata"]["kernelspec"] = {"display_name": "Python 3", "language": "python", "name": "python3"}
out = ROOT / "notebooks" / "claims_analysis.ipynb"
nbf.write(nb, out)
print("wrote", out)
